# Generated by Django 5.1.7 on 2025-03-20 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0003_jobapplication"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="role",
            field=models.CharField(
                choices=[("employee", "Employee"), ("employer", "Employer")],
                max_length=10,
            ),
        ),
    ]
