# Generated by Django 5.1.7 on 2025-03-20 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0004_alter_profile_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="role",
            field=models.CharField(
                choices=[("candidate", "Candidate"), ("employer", "Employer")],
                max_length=10,
            ),
        ),
    ]
